version: '3'

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: antlypls/zookeeper

  kafka:
    container_name: kafka
    hostname: kafka
    image: antlypls/kafka
    depends_on:
    - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1,error:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
    - "8080:8080"
    - "7077:7077"
    environment:
    - INIT_DAEMON_STEP=setup_spark
    - "constraint:node==<yourmasternode>"
    - "KAFKA_BROKERS=kafka:9092"
    - KAFKA_GROUP_ID=spark-streaming-demo
    - KAFKA_TOPIC=events

  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
    - spark-master
    ports:
    - "8081:8081"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "constraint:node==<yourmasternode>"

  spark-worker-2:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
    - spark-master
    ports:
    - "8082:8081"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "constraint:node==<yourmasternode>"

  spark-worker-3:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-3
    depends_on:
    - spark-master
    ports:
    - "8083:8081"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "constraint:node==<yourmasternode>"